name: Build Image
on:
  push:
    branches:
      - 2.2.14

jobs:
  build:
     name: Run Build Image
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
         with:
           fetch-depth: '0'
       - name: Log in to the Container registry
         uses: docker/login-action@v1.10.0
         with:
           registry: docker.io
           username: ${{ secrets.DOCKER_USER }}
           password: ${{ secrets.DOCKER_PASS }}
       - name: build
         run: |
           docker compose build
           docker push arugaldocker/milvus-env:amd64-centos7-20221214-66bf02d