name: Build Image
on:
  push:
    branches:
      - 2.2.14

jobs:
  build:
     name: Run Build Image
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
         with:
           fetch-depth: '0'
       - name: build
         run: |
           docker compose build
           docker images